In [1]:
import pandas as pd

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
df1=pd.read_csv("data2.csv")

In [4]:
df1

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [5]:
df1.dropna()

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [6]:
df1["Age"]=df1["Year"].astype(int)

In [7]:
df1

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Age
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,2023
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,2017
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,2016
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,2022
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,2018
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2018
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,2018
7,Hrithik Roshan,War,2019,Action,475,6.5,2019
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,2019
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2022
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,2017
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,2019

In [60]:
import pandas as pd

In [61]:
import warnings
warnings.filterwarnings("ignore")

In [62]:
df1=pd.read_csv("data_cleaning_sample.csv")

In [63]:
df1

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [64]:
df1=df1.dropna()
df1

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [65]:
df1["Age"]=df1["Age"].astype("category")

In [66]:
df1

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [67]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 7
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      object
 1   Age        5 non-null      category
 2   City       5 non-null      object
 3   Gender     5 non-null      object
 4   Email      5 non-null      object
 5   Join Date  5 non-null      object
dtypes: category(1), object(5)
memory usage: 377.0+ bytes

In [68]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 7
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      object
 1   Age        5 non-null      category
 2   City       5 non-null      object
 3   Gender     5 non-null      object
 4   Email      5 non-null      object
 5   Join Date  5 non-null      object
dtypes: category(1), object(5)
memory usage: 377.0+ bytes

In [69]:
df1

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [70]:
df1["Join Date"]=pd.to_datetime(df1["Join Date"],format="%d-%m-%Y")

In [71]:
df1

    Name   Age         City Gender              Email  Join Date
0  Alice  25.0     New York      F  alice@example.com 2021-05-01
2    Bob  30.0  Los Angeles      M    bob@example.com 2020-06-15
4  David  22.0       Mumbai      M  david@example.com 2019-11-12
6  Alice  25.0     New York      F  alice@example.com 2021-05-01
7  Alice  25.0     New York      F  alice@example.com 2021-05-01

In [72]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 7
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      object
 1   Age        5 non-null      category
 2   City       5 non-null      object
 3   Gender     5 non-null      object
 4   Email      5 non-null      object
 5   Join Date  5 non-null      datetime64[ns]
dtypes: category(1), datetime64[ns](1), object(4)
memory usage: 377.0+ bytes

In [73]:
df1["Year"]=df1["Join Date"].dt.year

In [74]:
df1

    Name   Age         City Gender              Email  Join Date  Year
0  Alice  25.0     New York      F  alice@example.com 2021-05-01  2021
2    Bob  30.0  Los Angeles      M    bob@example.com 2020-06-15  2020
4  David  22.0       Mumbai      M  david@example.com 2019-11-12  2019
6  Alice  25.0     New York      F  alice@example.com 2021-05-01  2021
7  Alice  25.0     New York      F  alice@example.com 2021-05-01  2021

In [75]:
df1["Month"]=df1["Join Date"].dt.month

In [76]:
df1

    Name   Age         City Gender              Email  Join Date  Year  Month
0  Alice  25.0     New York      F  alice@example.com 2021-05-01  2021      5
2    Bob  30.0  Los Angeles      M    bob@example.com 2020-06-15  2020      6
4  David  22.0       Mumbai      M  david@example.com 2019-11-12  2019     11
6  Alice  25.0     New York      F  alice@example.com 2021-05-01  2021      5
7  Alice  25.0     New York      F  alice@example.com 2021-05-01  2021      5

In [77]:
df1["Month_Name"]=df1["Join Date"].dt.month_name()

In [78]:
df1

,Name,Age,City,Gender,Email,Join Date,Year,Month,Month_Name
0,Alice,25.0,New York,F,alice@example.com,2021-05-01,2021,5,May
2,Bob,30.0,Los Angeles,M,bob@example.com,2020-06-15,2020,6,June
4,David,22.0,Mumbai,M,david@example.com,2019-11-12,2019,11,November
6,Alice,25.0,New York,F,alice@example.com,2021-05-01,2021,5,May
7,Alice,25.0,New York,F,alice@example.com,2021-05-01,2021,5,May

In [79]:
df1["Day_Name"]=df1["Join Date"].dt.day_name()

In [80]:
df1

,Name,Age,City,Gender,Email,Join Date,Year,Month,Month_Name,Day_Name
0,Alice,25.0,New York,F,alice@example.com,2021-05-01,2021,5,May,Saturday
2,Bob,30.0,Los Angeles,M,bob@example.com,2020-06-15,2020,6,June,Monday
4,David,22.0,Mumbai,M,david@example.com,2019-11-12,2019,11,November,Tuesday
6,Alice,25.0,New York,F,alice@example.com,2021-05-01,2021,5,May,Saturday
7,Alice,25.0,New York,F,alice@example.com,2021-05-01,2021,5,May,Saturday