In [1]:
! pip install pandas

Requirement already satisfied: pandas in c:\users\sumant\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sumant\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sumant\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sumant\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sumant\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\sumant\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# creating series

In [2]:
import pandas as pd

In [5]:
s1=pd.Series([1,2,3,4,5])

In [6]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
type(s1)

pandas.core.series.Series

In [8]:
s1=pd.Series([1,2,3,4,],index=["a","b","c","d"])

In [9]:
s1

a    1
b    2
c    3
d    4
dtype: int64

In [1]:
data={"Name":["Alice","bob","charlie"],"Age":["20","21","22"],"city":["mumbai","pune","gadag"]}
data

{'Name': ['Alice', 'bob', 'charlie'],
 'Age': ['20', '21', '22'],
 'city': ['mumbai', 'pune', 'gadag']}

In [11]:
type(data)

dict

# creating dataframe

In [18]:
df=pd.DataFrame(data)

In [19]:
df

      Name Age    city
0    Alice  20  mumbai
1      bob  21     pue
2  charlie  22   gadag

In [20]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [22]:
df.columns

Index(['Name', 'Age', 'city'], dtype='object')

In [16]:
df=pd.DataFrame(data,index=["person1","person2","person3"])
df

            Name Age    city
person1    Alice  20  mumbai
person2      bob  21     pue
person3  charlie  22   gadag

In [9]:
import pandas as pd
student={"name":["sangeeta","sumant","shree"],"rollno":[11,12,13],"div":["A","B","A"]}
df=pd.DataFrame(student)
df

       name  rollno div
0  sangeeta      11   A
1    sumant      12   B
2     shree      13   A

In [10]:
df=pd.DataFrame(student,index=["usn1","usn2","usn3"])
df

          name  rollno div
usn1  sangeeta      11   A
usn2    sumant      12   B
usn3     shree      13   A

In [11]:
df.index

Index(['usn1', 'usn2', 'usn3'], dtype='object')

In [13]:
df.columns

Index(['name', 'rollno', 'div'], dtype='object')

# creating dataframe from list

In [23]:
data=[[1,2,3],[4,5,6]]
data

[[1, 2, 3], [4, 5, 6]]

In [26]:
df=pd.DataFrame(data,columns=["A","B","C"],index=["D","E"])
df

   A  B  C
D  1  2  3
E  4  5  6

In [29]:
df.shape

(2, 3)

In [31]:
df=pd.read_excel("demo.xlsx")

In [32]:
df

       Name School  Marks
0   shubham     SA     65
1  sangeeta   GGHS     56
2     radha     GT     56
3    shreya    KLE     67
4   akshata    REC     84

In [35]:
df=pd.read_json("example.json")
df

    Name    Lang
0  Alice  Python
1    BOB    HTML

In [40]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
df=pd.DataFrame(arr,columns=["A","B","c"])
df

   A  B  c
0  1  2  3
1  4  5  6

# viewing data

In [49]:
import pandas as pd
df = pd.read_csv("leads-100.csv")
df.tail()

,Index,Account Id,Lead Owner,First Name,Last Name,Company,Phone 1,Phone 2,Email 1,Email 2,Website,Source,Deal Stage,Notes
95,96,879AA6f76aCcEeF,Mary Terry,Erica,Garrison,Clark-Sanford,+1-597-982-7250,(392)732-6167x122,clairegraves@campos.com,royclarence@navarro.net,http://arias-blackwell.com/,Other,New Lead,Condition system short author.
96,97,f8EBCd52d798D8f,Vincent Mcneil,Fernando,Dickerson,Gibbs and Sons,001-531-794-3476,215.384.8090x37887,yolanda77@rhodes.org,manuel38@bowen.com,https://www.clarke-valentine.com/,Networking Event,Re-engagement,Half top natural spend hold least.
97,98,bcCE5c7bEbdFfB2,Colin Choi,Sheila,Dyer,Frank-Wolf,965-697-8363x869,001-986-382-4669,vickieguerra@hanna.biz,lawsonkathleen@navarro-hudson.info,https://copeland.com/,Social Media,Proposal Sent,Suffer time still unit.
98,99,6cC0Dc8e4410B7E,Tony Beck,Cassie,Conrad,"Blake, Diaz and Weber",635-429-3322x8976,+1-431-607-4655x365,howeandrea@zhang.com,ynichols@bridges-grant.com,https://zimmerman.net/,Retargeting Ads,Negotiation,Administration great treat represent total.
99,100,DCabaF160FbDda8,Dillon Stephenson,Charlotte,Browning,Calderon LLC,(430)620-2165x822,+1-818-816-2088x7516,hbooth@ferrell-baker.com,carriekerr@spears.com,http://www.patton-pollard.com/,Content Marketing,Negotiation,Talk executive hear only but book later.

In [51]:
iris = 'http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
df=pd.read_csv(iris)
df

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [52]:
df.head()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [53]:
df.tail()

     5.1  3.5  1.4  0.2     Iris-setosa
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

In [55]:
df.columns

Index(['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], dtype='object')

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   5.1          149 non-null    float64
 1   3.5          149 non-null    float64
 2   1.4          149 non-null    float64
 3   0.2          149 non-null    float64
 4   Iris-setosa  149 non-null    object
dtypes: float64(4), object(1)
memory usage: 5.9+ KB

In [57]:
df.describe()

              5.1         3.5         1.4         0.2
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [58]:
df.shape

(149, 5)

# DAY - 2

# data selection

In [7]:
import pandas as pd

In [8]:
df=pd.read_csv("data2.csv")
df.tail()

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

# selecting column

In [9]:
df["Actor"]

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [10]:
type(df["Actor"])

pandas.core.series.Series

In [11]:
df[["Actor","IMDb"]]

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [12]:
type(df[["Actor","IMDb"]])

pandas.core.frame.DataFrame

# selecting rows

In [13]:
df.loc[0]

Actor                   Shah Rukh Khan
Film                           Pathaan
Year                              2023
Genre                           Action
BoxOffice(INR Crore)              1050
IMDb                               7.2
Name: 0, dtype: object

In [14]:
df.iloc[0]

Actor                   Shah Rukh Khan
Film                           Pathaan
Year                              2023
Genre                           Action
BoxOffice(INR Crore)              1050
IMDb                               7.2
Name: 0, dtype: object

In [15]:
df1=pd.DataFrame([[1,2,3],[4,5,7]],columns=["A","B","C"],index=["D","E"])
df1

   A  B  C
D  1  2  3
E  4  5  7

In [16]:
df1.iloc[0] #idex numbers

A    1
B    2
C    3
Name: D, dtype: int64

In [17]:
df1.loc["E"] # assign letter

A    4
B    5
C    7
Name: E, dtype: int64

In [18]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

# selecting specific rows and column

In [19]:
df.loc[0,"Actor"]

'Shah Rukh Khan'

In [20]:
df.iloc[0,0]

'Shah Rukh Khan'

In [21]:
df.loc[1,"Film"]

'Tiger Zinda Hai'

In [22]:
df.iloc[0,1]

'Pathaan'

In [23]:
df.loc[0:2,["Actor","IMDb"]]

            Actor  IMDb
0  Shah Rukh Khan   7.2
1     Salman Khan   6.0
2      Aamir Khan   8.4

In [24]:
df.iloc[0:2,[0,5]]

            Actor  IMDb
0  Shah Rukh Khan   7.2
1     Salman Khan   6.0

In [25]:
df.loc[0:2,"Actor":"Genre"]

            Actor             Film  Year      Genre
0  Shah Rukh Khan          Pathaan  2023     Action
1     Salman Khan  Tiger Zinda Hai  2017     Action
2      Aamir Khan           Dangal  2016  Biography

In [26]:
df.loc[0:5,"Actor":"Genre"]

                Actor             Film  Year       Genre
0      Shah Rukh Khan          Pathaan  2023      Action
1         Salman Khan  Tiger Zinda Hai  2017      Action
2          Aamir Khan           Dangal  2016   Biography
3       Ranbir Kapoor       Brahmastra  2022     Fantasy
4       Ranveer Singh        Padmaavat  2018  Historical
5  Ayushmann Khurrana        Andhadhun  2018    Thriller

In [27]:
df.iloc[0:5,[0,1,2,3]]

            Actor             Film  Year       Genre
0  Shah Rukh Khan          Pathaan  2023      Action
1     Salman Khan  Tiger Zinda Hai  2017      Action
2      Aamir Khan           Dangal  2016   Biography
3   Ranbir Kapoor       Brahmastra  2022     Fantasy
4   Ranveer Singh        Padmaavat  2018  Historical

In [28]:
df.iloc[0:3,0:4]

            Actor             Film  Year      Genre
0  Shah Rukh Khan          Pathaan  2023     Action
1     Salman Khan  Tiger Zinda Hai  2017     Action
2      Aamir Khan           Dangal  2016  Biography

In [29]:
df.loc[0:2,"Actor":"Genre"]

            Actor             Film  Year      Genre
0  Shah Rukh Khan          Pathaan  2023     Action
1     Salman Khan  Tiger Zinda Hai  2017     Action
2      Aamir Khan           Dangal  2016  Biography

# fast access "at" and "iat"

In [30]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [32]:
df.at[0,"Actor"]

'Shah Rukh Khan'

In [33]:
df.iat[0,0]

'Shah Rukh Khan'

# data filtering

In [34]:
df["IMDb"]>6

0      True
1     False
2      True
3     False
4      True
5      True
6      True
7      True
8      True
9     False
10     True
11     True
Name: IMDb, dtype: bool

In [37]:
df["IMDb"]<6

0     False
1     False
2     False
3      True
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
Name: IMDb, dtype: bool

In [38]:
df[df["IMDb"]>6]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [39]:
df[df["IMDb"]<6]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9

In [41]:
df[df["Year"]>2017]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [48]:
df[(df["Year"]>2017)&(df["IMDb"]>6)]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [51]:
df.query("Year>2017 & IMDb>6")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [52]:
df.query("Year > 2017")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [54]:
df.query("Actor== 'Hrithik Roshan'")

            Actor Film  Year   Genre  BoxOffice(INR Crore)  IMDb
7  Hrithik Roshan  War  2019  Action                   475   6.5

In [55]:
df.query('Actor=="Hrithik Roshan"')

            Actor Film  Year   Genre  BoxOffice(INR Crore)  IMDb
7  Hrithik Roshan  War  2019  Action                   475   6.5

In [59]:
df1=pd.DataFrame([[1,2,3],[4,5,6]],columns=["A B","C","D"])
df1

   A B  C  D
0    1  2  3
1    4  5  6

In [60]:
df1.query("`A B`==1")

   A B  C  D
0    1  2  3

In [61]:
year=2017
df.query("Year>@year")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [62]:
df.query("2017 < Year < 2023")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [70]:
df.query("Year > 2022")

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

In [2]:
df

NameError: name 'df' is not defined

In [1]:
df.query("2017 and 2023")

NameError: name 'df' is not defined