In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("data2.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [4]:
df.sort_values("Year")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [5]:
df.sort_values("Year",ascending=False)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [7]:
df.sort_values(["Year","IMDb"])

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [9]:
df.sort_values(["Year","IMDb"],ascending=[True,False])

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Hrithik Roshan,War,2019,Action,475,6.5
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [10]:
df1=df.sort_values("Year")

In [11]:
df1

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [12]:
df1.reset_index()

,index,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
3,4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
4,5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
5,6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
6,7,Hrithik Roshan,War,2019,Action,475,6.5
7,8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
9,3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
10,9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [13]:
df1.reset_index(drop=True)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
4,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
5,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
6,Hrithik Roshan,War,2019,Action,475,6.5
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [17]:
df1.reset_index(drop=True,inplace=True)

In [18]:
df1

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
3,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
4,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
5,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
6,Hrithik Roshan,War,2019,Action,475,6.5
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
9,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
10,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [19]:
df2=df.sort_values("Year")

In [20]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [21]:
df2.sort_index()

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [23]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [28]:
df.sort_values("IMDb",ascending=False,inplace=True)

In [29]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,12.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,11.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,10.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,9.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,8.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.5
7,Hrithik Roshan,War,2019,Action,475,6.5,5.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0

In [24]:
df["Rank"]=df["IMDb"].rank()

In [25]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,8.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,12.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,11.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,9.0
7,Hrithik Roshan,War,2019,Action,475,6.5,5.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.5
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,10.0

In [30]:
df["Rank"]=df["IMDb"].rank(ascending=False)

In [31]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.5
7,Hrithik Roshan,War,2019,Action,475,6.5,8.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,9.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,10.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,11.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,12.0

In [33]:
df["Rank"]=df["IMDb"].rank(ascending=False,method="dense")

In [34]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
7,Hrithik Roshan,War,2019,Action,475,6.5,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0

In [36]:
df["Rank"]=df["Rank"].astype(int)

In [37]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6
7,Hrithik Roshan,War,2019,Action,475,6.5,7
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11

# renaming column and reordering column

In [38]:
df.rename(columns={"Actor":"Hero"})

,Hero,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6
7,Hrithik Roshan,War,2019,Action,475,6.5,7
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11

In [39]:
df.rename(columns={"Actor":"Hero"},inplace=True)

In [40]:
df

,Hero,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6
7,Hrithik Roshan,War,2019,Action,475,6.5,7
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11

In [41]:
df.rename(index={0:"Row1"})

,Hero,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4
Row1,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6
7,Hrithik Roshan,War,2019,Action,475,6.5,7
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11

# df.columns(["All the column Name"])

In [46]:
df.columns=["Actor","Movie","Year","Genre","Collection","IMDB","Rank"]

In [47]:
df

,Actor,Movie,Year,Genre,Collection,IMDB,Rank
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6
7,Hrithik Roshan,War,2019,Action,475,6.5,7
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11

In [48]:
df=df[["Movie","Actor","Year","Collection","Genre","Rank","IMDb"]]

KeyError: "['IMDb'] not in index"